# Don't change this! Version used to track needed updates.
version = 0
nihilBladeNothingnessChance = 0.15
nullAndVoidHitChance = 0.15
voidStrikeHitChance = 0.15
voidStrikeDamageMultiplier = 3.0
trueSmiteDamageMultiplier = 4.0
fleshRendingCriticalChance = 0.2
radiantBastionShieldChance = 0.333333

[enabledModifiers]
"imbued_gear:wisened" = true
"imbued_gear:very_experienced" = true
"imbued_gear:experienced" = true
"imbued_gear:inexperienced" = true
"imbued_gear:inept" = true
"imbued_gear:mana_vampiric" = true
"imbued_gear:mana_draining" = true
"imbued_gear:mana_reactive" = true
"imbued_gear:cowardly" = true
"imbued_gear:scholarly" = true
"imbued_gear:protection_from_evil" = true
"imbued_gear:nothingness" = true
"imbued_gear:null_space" = true
"imbued_gear:radiant_bastion" = true
"imbued_gear:radiant_devotion" = true
"imbued_gear:radiant_absolution" = true
"imbued_gear:flesh_rending" = true
"imbued_gear:kindled" = true

[gear]
manaVampiricHitChance = 0.15
manaVampiricHitAmount = 10
manaVampiricKillAmount = 15
manaDrainingHitChance = 0.15
manaDrainingHitAmount = 7
manaDrainingKillAmount = 10
manaReactiveAmount = 1