# Don't change this! Version used to track needed updates.
version = 0
oceanBossLootTables = [
    "minecraft:entities/elder_guardian"
]
oceanChestLootTables = [
    "minecraft:chests/shipwreck_supply",
    "minecraft:chests/shipwreck_map",
    "minecraft:chests/shipwreck_treasure",
    "minecraft:chests/underwater_ruin_small",
    "minecraft:chests/underwater_ruin_big",
    "minecraft:chests/ruined_portal",
    "minecraft:chests/buried_treasure",
    "mostructures:pirate_ship_cargo_misc"
]
witherUniqueChance = 0.01
oceanBossUniqueChance = 0.005
chestUniqueChance = 5.0E-4
basicHarpoonChance = 0.1
oceanHarpoonChance = 0.1
strongHarpoonChance = 0.075

[harpoon]
boneBaseDamage = 5.0
prismarineBaseDamage = 6.0
diamondBaseDamage = 7.0
powerAdderPerLevel = 1.25
powerBaseAdder = 1.0